// animal icons
export { default as BeeIcon } from './animals/bee.svg'
export { default as CatIcon } from './animals/cat.svg'
export { default as ChickenIcon } from './animals/chicken.svg'
export { default as CowIcon } from './animals/cow.svg'
export { default as DogIcon } from './animals/dog.svg'
export { default as DuckIcon } from './animals/duck.svg'
export { default as FishIcon } from './animals/fish.svg'
export { default as GoatIcon } from './animals/goat.svg'
export { default as GooseIcon } from './animals/goose.svg'
export { default as HorseIcon } from './animals/horse.svg'
export { default as ParrotIcon } from './animals/parrot.svg'
export { default as PigIcon } from './animals/pig.svg'
export { default as PigeonIcon } from './animals/pigeon.svg'
export { default as RabbitIcon } from './animals/rabbit.svg'
export { default as SheepIcon } from './animals/sheep.svg'
export { default as TurkeyIcon } from './animals/turkey.svg'
export { default as TurtleIcon } from './animals/turtle.svg'

// ui icons
export { default as SearchIcon } from './ui/search.svg'
export { default as CircleSmall } from './ui/circle-small.svg'
export { default as ArrowToggle } from './ui/arrow-toggle.svg'
